CREATE TABLE Bookings  (
    bookingId SERIAL PRIMARY KEY,
    clientId INT NOT NULL DEFAULT 0,
    hotelId INT NOT NULL DEFAULT 0,
    roomId INT NOT NULL DEFAULT 0,
    roomCategory TEXT NOT NULL DEFAULT 'Standard',
    Price  INT NOT NULL DEFAULT 1000,
    bookingStartTimestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    bookingFinishTimestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW() + INTERVAL '1 day',
    creationTimestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
